### ISSUE TITLE
What tools can be used to analyze the dump file

### ISSUE THREAD

**Issue by burne-muz** [Sysinternals/ProcDump-for-Linux#105]
I have successfully generated files on debian, but what analysis tool should I use?
I've tried windbg, and it doesn't seem to work.

**Comment by jahabibi** [comment]
The core dump files that are generated by Procdump for Linux are ELF format, not windows dump format. This is why `windbg` cannot be used to analyze them. However, since the ELF format is the Linux standard there are many utilities that can be used to analyze these dumps. For example `gdb` and `lldb` are two very popular choices.
