### ISSUE TITLE
Install step on Linux Mint (Ubuntu 20.04 base) fails as lsb_release only shows "20" instead of "20.04"

### ISSUE THREAD

**Issue by allywilson** [Sysinternals/ProcDump-for-Linux#93]
### Expected behavior
Download of DEB package

### Actual behavior
Empty/0-byte file created (no error).

### Steps to reproduce the behavior
1. `wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb`
2. File is created but is empty.
3. The command `lsb_release -rs` returns "20" instead of "20.04"

### System information (e.g., distro, kernel version, etc.)
Linux 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"

It's probably a Linux Mint quirk of lsb-release, but thought I should mention it.

**Comment by jahabibi** [comment]
The instructions you cited are specific to Ubuntu and are incompatible with Linux Mint 20. However, since Linux Mint 20 is based on Ubuntu Focal (20.04) we can adjust them slightly to work. To do this we manually insert the version string `lsb_release -rs` would provide to pull from the Microsoft Ubuntu 20.04 package repository. This would then look like the following:

1. `wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb`
2. `sudo dpkg -i packages-microsoft-prod.deb`
3. `sudo apt update`
4. `sudo apt install procdump`
